version: '3.8'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data            # ← Persisted data (RDB/AOF)
      - ./src/main/resources/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro  # ← Config

volumes:
  redis-data:
    driver: local