spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: localhost
  port: 8085

h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
    com:
      portfolioAPI:
        portfolioapi=DEBUG:
